language: generic
sudo: required
services:
- docker
env:
  - DOCKER_USERNAME=tommywenjiezhang
before_install:
- docker build -f Dockerfile.dev -t tommywenjiezhang/flask_dev  .
script:
- docker run -e CI=true --name docker_python_pipeline_setup tommywenjiezhang/flask_dev python3 -m pytest
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
