#!/bin/bash
sudo docker login -u "$HEROKU_USERNAME" --password="$HEROKU_PASSWORD" registry.heroku.com
sudo docker tag tommywenjiezhang/flask_docker_setup registry.heroku.com/docker-flask-pipeline/web
sudo docker push registry.heroku.com/docker-flask-pipeline/web
